export const clerkAppearance = {
  layout: {
    unsafe_disableDevelopmentModeWarnings: true,
    showOptionalFields: false,
    logoPlacement: "none" as const,
    brandingMode: "none" as const,
  },
  variables: {
    colorBackground: "#f5f0e8",
    colorText: "#1a1410",
    colorPrimary: "#ff2d20",
    colorDanger: "#ff2d20",
    colorInputBackground: "#f5f0e8",
    colorInputText: "#1a1410",
    colorTextSecondary: "#6b5e52",
    fontFamily: "'IBM Plex Mono', monospace",
    fontFamilyButtons: "'Archivo Black', sans-serif",
    borderRadius: "0px",
    spacingUnit: "16px",
  },
  elements: {
    card: {
      background: "#f5f0e8",
      border: "2px solid #1a1410",
      borderRadius: "0",
      boxShadow: "6px 6px 0 #1a1410",
      padding: "32px",
    },
    headerTitle: {
      fontFamily: "'Archivo Black', sans-serif",
      fontSize: "28px",
      textTransform: "uppercase",
      letterSpacing: "-0.02em",
      color: "#1a1410",
    },
    headerSubtitle: {
      fontFamily: "'IBM Plex Mono', monospace",
      fontSize: "12px",
      color: "#6b5e52",
    },
    formFieldLabel: {
      fontFamily: "'IBM Plex Mono', monospace",
      fontSize: "11px",
      letterSpacing: "0.18em",
      textTransform: "uppercase",
      fontWeight: "700",
      color: "#1a1410",
    },
    formFieldInput: {
      fontFamily: "'IBM Plex Mono', monospace",
      fontSize: "14px",
      background: "#f5f0e8",
      border: "2px solid #1a1410",
      borderRadius: "0",
      color: "#1a1410",
      padding: "10px 12px",
      boxShadow: "none",
      outline: "none",
    },
    formFieldInputShowPasswordButton: {
      color: "#6b5e52",
    },
    formButtonPrimary: {
      fontFamily: "'Archivo Black', sans-serif",
      fontSize: "14px",
      textTransform: "uppercase",
      letterSpacing: "0.04em",
      background: "#ff2d20",
      border: "2px solid #1a1410",
      borderRadius: "0",
      color: "#f5f0e8",
      boxShadow: "none",
      padding: "12px 20px",
    },
    socialButtonsBlockButton: {
      fontFamily: "'IBM Plex Mono', monospace",
      fontSize: "13px",
      background: "#f5f0e8",
      border: "2px solid #1a1410",
      borderRadius: "0",
      color: "#1a1410",
      boxShadow: "none",
    },
    socialButtonsBlockButtonText: {
      fontFamily: "'IBM Plex Mono', monospace",
      fontWeight: "500",
    },
    dividerLine: {
      background: "#1a1410",
      height: "2px",
    },
    dividerText: {
      fontFamily: "'IBM Plex Mono', monospace",
      fontSize: "11px",
      letterSpacing: "0.1em",
      textTransform: "uppercase",
      color: "#6b5e52",
    },
    footerActionText: {
      fontFamily: "'IBM Plex Mono', monospace",
      fontSize: "12px",
      color: "#6b5e52",
    },
    footerActionLink: {
      fontFamily: "'IBM Plex Mono', monospace",
      fontSize: "12px",
      color: "#ff2d20",
      textDecoration: "underline",
    },
    identityPreviewText: {
      fontFamily: "'IBM Plex Mono', monospace",
      fontSize: "13px",
    },
    formFieldError: {
      fontFamily: "'IBM Plex Mono', monospace",
      fontSize: "12px",
      color: "#ff2d20",
    },
    alertText: {
      fontFamily: "'IBM Plex Mono', monospace",
      fontSize: "12px",
    },
    formResendCodeLink: {
      fontFamily: "'IBM Plex Mono', monospace",
      fontSize: "12px",
      color: "#ff2d20",
    },
    footer: {
      display: "none",
    },
  },
};
